# Generated by Django 2.2.5 on 2019-10-13 13:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Imagen')),
                ('text', models.TextField(verbose_name='Entrada')),
                ('published', models.DateField(default=datetime.datetime(2019, 10, 13, 13, 9, 20, 706271, tzinfo=utc), verbose_name='Publicado el ')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha creación')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha edición')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Fecha edición'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
