# Generated by Django 2.2.5 on 2019-10-20 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191013_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='get_posts', to='blog.Category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2019, 10, 20, 6, 56, 3, 432727, tzinfo=utc), verbose_name='Publicado el '),
        ),
    ]
