# Generated by Django 2.2.5 on 2019-10-23 04:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191020_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2019, 10, 23, 4, 59, 33, 649878, tzinfo=utc), verbose_name='Publicado el '),
        ),
    ]
