# Generated by Django 2.2.5 on 2019-10-23 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191023_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2019, 10, 23, 5, 2, 8, 773897, tzinfo=utc), verbose_name='Publicado el '),
        ),
    ]
