# Generated by Django 2.2.5 on 2019-11-01 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191027_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2019, 11, 1, 7, 50, 49, 250875, tzinfo=utc), verbose_name='Publicado el '),
        ),
    ]
